In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split, GridSearchCV

In [2]:
df = pd.read_csv('https://stepik.org/media/attachments/course/4852/invasion.csv')
df

,class,g_reflection,i_reflection,speed,brightness,time_of_observance,volume
0,transport,2.190672,6.716633,62.168208,0.347465,158221,44.932446
1,transport,3.453276,8.995909,62.994707,0.590094,385972,41.568300
2,transport,2.432994,6.938691,62.245807,0.329288,446482,40.123467
3,fighter,6.083763,3.019459,18.474555,0.174738,210125,11.384865
4,fighter,12.876769,2.452950,195.805771,0.150446,23109,11.328806
...,...,...,...,...,...,...,...
495,fighter,9.901731,7.162124,58.095069,0.145065,395762,12.901909
496,transport,3.574132,7.118835,62.928159,0.469670,435926,39.926551
497,fighter,9.186049,4.580781,412.102112,0.108195,299594,12.178203
498,fighter,8.278256,8.353756,268.121561,0.132661,361911,13.905809
499,transport,0.860820,8.014988,62.292486,0.304896,364601,46.151972

In [3]:
X_test = pd.read_csv('https://stepik.org/media/attachments/course/4852/operative_information.csv')
X_test

,g_reflection,i_reflection,speed,brightness,time_of_observance,volume
0,7.516543,3.916691,513.954279,0.177247,105908,13.267224
1,4.322988,6.967689,63.752970,0.545922,277855,39.833130
2,4.595724,9.098297,62.233948,0.389201,160662,42.014556
3,2.689675,7.964869,62.475495,0.541081,162092,42.056829
4,8.075576,5.169719,336.441261,0.174757,466853,11.779813
...,...,...,...,...,...,...
1495,11.755466,5.583147,325.069957,0.170644,388400,13.210917
1496,12.220137,4.023177,439.975574,0.163958,195305,13.819358
1497,1.611053,7.864930,65.025106,0.430021,307856,47.369083
1498,7.114131,5.532188,391.178342,0.150117,51590,12.447761
1499,3.804275,8.038047,62.345396,0.564630,97284,44.671211

In [4]:
pd.unique(df['class'])

array(['transport', 'fighter', 'cruiser'], dtype=object)

In [5]:
X_train = df.drop(['class'], axis=1)
y_train = df['class']

In [6]:
clf = RandomForestClassifier(random_state=0)

In [7]:
clf.fit(X_train, y_train)

RandomForestClassifier(random_state=0)

In [8]:
y_pred = clf.predict(X_test)

In [9]:
s = pd.Series(y_pred).value_counts()
s

fighter      675
transport    595
cruiser      230
dtype: int64

In [10]:
for i in s[::-1]:
    print(i, end=' ')

230 595 675

In [11]:
feature_importances = clf.feature_importances_
feature_importances_df = pd.DataFrame({'features': list(X_train),
                                      'feature_importances': feature_importances}) #Ð²Ð°Ð¶Ð½Ñ‹Ðµ Ð¿ÐµÑ€ÐµÐ¼ÐµÐ½Ð½Ñ‹Ðµ
feature_importances_df.sort_values('feature_importances', ascending=False)

             features  feature_importances
5              volume             0.323855
3          brightness             0.278944
0        g_reflection             0.185294
2               speed             0.117529
1        i_reflection             0.093694
4  time_of_observance             0.000685